<?$APPLICATION->IncludeComponent(
	"bitrix:catalog",
	"template1",
	Array(
		"ACTION_VARIABLE" => "action",
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BASKET_URL" => "/personal/cart/",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "N",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CONVERT_CURRENCY" => "N",
		"DETAIL_BROWSER_TITLE" => "-",
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_PROPERTY_CODE" => array(0=>"ZHIL_COM",1=>"IS_AREND",2=>"PODTYPE",3=>"SPALEN",4=>"INVESTIGATION",5=>"LOCATION",6=>"VID",7=>"PARKING",8=>"WATER",9=>"FLOOR",10=>"HOUSE_AREA",11=>"AREA",12=>"SEA_LENGTH",13=>"VID_ON_SEA",14=>"TYPE",15=>"ZASTR_AREA",16=>"CURRENCY",17=>"BIG_TOWNS",18=>"LANGUAGE",19=>"CAPITAL",20=>"PHONE_CODE",21=>"",),
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "Дата создания",
		"ELEMENT_SORT_FIELD2" => "sort",
		"ELEMENT_SORT_ORDER" => "desc",
		"ELEMENT_SORT_ORDER2" => "asc",
		"FILTER_FIELD_CODE" => array(0=>"DATE_CREATE",1=>"",),
		"FILTER_NAME" => "arrFilter",
		"FILTER_PRICE_CODE" => array(),
		"FILTER_PROPERTY_CODE" => array(0=>"ZHIL_COM",1=>"IS_AREND",2=>"PODTYPE",3=>"SPALEN",4=>"PRICE",5=>"INVESTIGATION",6=>"ELIT",7=>"LOCATION",8=>"VID",9=>"TYPE",10=>"SPEC",11=>"",),
		"HIDE_NOT_AVAILABLE" => "N",
		"IBLOCK_ID" => "4",
		"IBLOCK_TYPE" => "catalog",
		"INCLUDE_SUBSECTIONS" => "A",
		"LINE_ELEMENT_COUNT" => "2",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"LINK_IBLOCK_ID" => "",
		"LINK_IBLOCK_TYPE" => "",
		"LINK_PROPERTY_SID" => "",
		"LIST_BROWSER_TITLE" => "-",
		"LIST_META_DESCRIPTION" => "-",
		"LIST_META_KEYWORDS" => "-",
		"LIST_PROPERTY_CODE" => array(0=>"PRICE",1=>"",),
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "modern_adv",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "8",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(),
		"PRICE_VAT_INCLUDE" => "N",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"SECTION_COUNT_ELEMENTS" => "N",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_TOP_DEPTH" => "1",
		"SEF_FOLDER" => "/catalog/",
		"SEF_MODE" => "Y",
		"SEF_URL_TEMPLATES" => array("sections"=>"","section"=>"#SECTION_CODE#/","element"=>"#SECTION_CODE#/#ELEMENT_CODE#_#ELEMENT_ID#/","compare"=>"compare/",),
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"SHOW_TOP_ELEMENTS" => "N",
		"USE_COMPARE" => "N",
		"USE_ELEMENT_COUNTER" => "N",
		"USE_FILTER" => "Y",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "Y",
		"USE_REVIEW" => "N",
		"USE_STORE" => "N"
	)
);?>
<blockquote style="margin: 0 0 0 40px; border: none; padding: 0px;">
	<blockquote style="margin: 0 0 0 40px; border: none; padding: 0px;">
		<blockquote style="margin: 0 0 0 40px; border: none; padding: 0px;">
			<blockquote style="margin: 0 0 0 40px; border: none; padding: 0px;">
				<blockquote style="margin: 0 0 0 40px; border: none; padding: 0px;">
					<h2><span style="color: #0072bc; background-color: #ffffff;">&nbsp; &nbsp; Новости недвижимости:&nbsp;</span></h2>
				</blockquote>
			</blockquote>
		</blockquote>
	</blockquote>
</blockquote>
 <span style="background-color: #ffffff; color: #0072bc;"> </span><a href="http://www.advecs-zn.com/news/"><span style="color: #00aeef;"><span style="background-color: #ffffff; color: #fff100;"><span style="color: #363636;"><i><span style="color: #0072bc;">Посмотреть все</span></i></span></span></span></a><span style="color: #438ccb; background-color: #fff799;"><br>
 </span> <?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"official",
	Array(
		"ACTIVE_DATE_FORMAT" => "d-m-Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "N",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => array("","[COUNTRY]",""),
		"FILTER_NAME" => "[COUNTRY]",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "1",
		"IBLOCK_TYPE" => "news",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "Y",
		"NEWS_COUNT" => "6",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "",
		"PAGER_TITLE" => "Новости",
		"PARENT_SECTION" => "country",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => array("",""),
		"SET_BROWSER_TITLE" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "",
		"SORT_ORDER1" => "",
		"SORT_ORDER2" => ""
	)
);?><br>
 &nbsp;<a href="http://www.advecs-zn.com/news/"><span style="color: #00aeef;"><span style="background-color: #ffffff; color: #fff100;"><span style="color: #363636;"><i><span style="color: #0072bc;">Посмотреть все</span></i></span></span></span></a><br>